### PR TITLE
Fix function comments based on best practices from Effective Go

### PR DESCRIPTION
**Pull request by BlakeMScurr**
Every exported function in a program should have a doc comment. The first sentence should be a summary that starts with the name being declared.
From [effective go](https://golang.org/doc/effective_go.html#commentary).

I generated this with [CodeLingo](https://codelingo.io) and I'm keen to get some feedback, _but this is automated so feel free to close it and just say "**opt out**" to opt out of future CodeLingo outreach PRs._

### CODE REVIEW

**Comment by BlakeMScurr** [comment]
Looks like the vast majority of these changes are good like [this](https://github.com/lunixbochs/usercorn/pull/316/files#diff-634cf327e983c35fbfa71713b0490622R25), [this](https://github.com/lunixbochs/usercorn/pull/316/files#diff-547ebfb5de3b51a58356bc41803e2233R81), and [this](https://github.com/lunixbochs/usercorn/pull/316/files#diff-35caf756d4fffd7f216c191413ad9a47R80). 

But I would say [this particular change]() makes the comment clunkier because we end up repeating the noun in verb form. We're trading readability and beauty against conforming to standards, do you think it's worth it? Can you think of any way that I can rewrite your comment? If you can, and this is a blocking issue, I can work on a fix to my script ASAP and update the PR.

Let me know if you think this was useful :smile:

Note: I've only updated functions that I *know* CodeLingo can rewrite nicely, but you can install it [from the GitHub marketplace](https://github.com/apps/codelingo) to review your PRs automatically and find all issues.

**Comment by lunixbochs** [comment]
Does usercorn have any actual third party users? I'm dubious that any functions can really be considered exported until it does

**Comment by BlakeMScurr** [comment]
Hi @lunixbochs :smile:

The functions in question are public. Why would they be public if they weren't intended to be used by another package? Good package design and commenting is important even if the packages are only being imported by related projects and packages, right?

**Comment by lunixbochs** [comment]
The "other packages" using it are components in the same repository. This project is basically a complicated operating system kernel with many internal packages.

**Comment by BlakeMScurr** [comment]
Well, the more complicated the project the more important it is to have good separation of concerns right? And nice comments on public methods are a key way of identifying how components fit together.

However, I'm happy to defer to a contributor's knowledge of the project - I won't be offended if you close this :laughing:

**Pull request closed without merging**
