### PR TITLE
README: Add cmake as dependency

### PR DESCRIPTION
**Pull request by Grazfather**

### CODE REVIEW

**Comment by lunixbochs** [comment]
hmm, cmake is only really a dependency if you `make deps`, which in itself negates the other requirements.

**Comment by lunixbochs** [comment]
something like "the latest version of these dependencies can be downloaded and compiled into the deps/ folder using `make deps`, which depends on cmake"?

**Comment by lunixbochs** [comment]
I rolled this back, didn't realize you were PR'ing master. Please PR unstable next time :)

**Comment by Grazfather** [comment]
Oh, I didn't know you only merge from unstable. I wanted this in master since that's the set of instructions people see when they first visit the github page.

**Comment by lunixbochs** [comment]
I merged unstable, it was about time anyway.

**Comment by Grazfather** [comment]
Cool 👌

**Pull request merged**
