### PR TITLE
Update README.md with LOC count

### PR DESCRIPTION
**Pull request by petevine**
Generated with tokei; this info might be put in a new topmost file and regenerated automatically.

### CODE REVIEW

**Comment by lunixbochs** [comment]
This is interesting but I'm not sure what it gets me - it's also super awkward to regenerate all the time (and won't merge), so I don't see the benefit over a user running it themselves.

**Comment by petevine** [comment]
The statistic looked kind of clean, so I thought it mind be something worth advertising.

**Comment by petevine** [comment]
If I wanted to count `go` dependencies too, would adding `go/src/github` be a good idea or would I be including lots of unused code? I have a similar idea to [counting](https://github.com/Aaronepower/tokei/issues/33#issuecomment-220857373) rust's `.cargo` directory.

**Comment by lunixbochs** [comment]
`go/src/github` will reference code not used by Usercorn
If you look at `make get` it should give you a list of direct dependencies.

I don't really want to merge this because I don't want a bunch of commits maintaining it. The only way I'd include a sloc count in the readme is via an image badge that automatically updates itself without new commits... like how coveralls displays the code coverage for example.

**Comment by petevine** [comment]
Sure, I thought you were keeping it open for publicity :)

I meant a fresh build with `make`, with no previous go downloads - will that be okay or still contain too much unused code?

**Comment by lunixbochs** [comment]
If you `rm -rf $GOPATH/go/src/` then make usercorn it should be accurate.

**Comment by petevine** [comment]
OK, here's an update then!

````
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Go                    149         9163         7886          298          979
 Makefile                1           26           18            0            8
 Python                  2          154          125            2           27
 YAML                    1           20           17            0            3
-------------------------------------------------------------------------------
 Total                 153         9363         8046          300         1017
-------------------------------------------------------------------------------
````

and including the dependencies (not sure about the entirety of `golang.org/x/crypto`, so not included):
````
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 BASH                    1            8            6            1            1
 C Header                6         3435         2939          400           96
 Go                    319        38753        33641         1790         3322
 Makefile                1           26           18            0            8
 Python                  4          284          226           11           47
 YAML                    7           89           82            0            7
-------------------------------------------------------------------------------
 Total                 338        42595        36912         2202         3481
-------------------------------------------------------------------------------

````

**Pull request closed without merging**
