### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by petevine**

### CODE REVIEW

**Comment by lunixbochs** [comment]
This shouldn't be necessary for normal use, as `make all` depends on `make get`.

**Comment by petevine** [comment]
I was following the instructions in the README and using `go build -i -o usercorn ./go/usercorn` which wasn't enough. For anyone new to go it's going to be helpful to know about it - unless you wish to clarify the preferred build method.

**Comment by lunixbochs** [comment]
`go build -i -o usercorn ./go/usercorn` is only required if you don't have make, which is only likely to happen on Windows.

**Comment by petevine** [comment]
That's why README needs updating. I thought they were fully equivalent.

**Comment by petevine** [comment]
And how would someone on Windows resolve this issue without make?

**Comment by lunixbochs** [comment]
Manually `go get -u` the outdated dependency. That's why I consider it a bug in Go :)

**Comment by petevine** [comment]
All right, I'm going to close but please do think of some better clarification.

**Comment by petevine** [comment]
I see - README should make it clear then the `go get` method is the preferred one whereas the others may require updating dependencies.

**Comment by petevine** [comment]
And BTW, could you add a hint when it's necessary/advantageous to rebuild libunicorn? I don't think the build scripts do that at present.

**Comment by lunixbochs** [comment]
once unicorn is stable it shouldn't matter. I don't think I need anything besides the map_ptr api anyway.

**Comment by petevine** [comment]
From the API point of view there's no problem but surely it makes sense to rebuild unicorn after a while?

**Comment by lunixbochs** [comment]
If you think you have a bug, update Unicorn and retest before reporting it. There's not much I can do otherwise unless I vendor it, which makes no sense to me. I personally haven't been updating unless I hit a bug or need an API change. I wouldn't recommend worrying too much about it.

**Pull request closed without merging**
